default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter: postgresql
  encoding: unicode
  database: firstprojectdbtest
  pool: 5
  username: firstprojectuser
  password: firstpassword

development:
  adapter: postgresql
  encoding: unicode
  database: firstprojectdbdev
  pool: 5
  username: firstprojectuser
  password: firstpassword

production:
  adapter: postgresql
  encoding: unicode
  database: firstprojectdbprod
  pool: 5
  username: firstprojectuser
  password: firstpassword